import Head from 'next/head'
import Image from 'next/image'
import Featured from '../components/Featured'
import styles from '../styles/Home.module.css'
import PizzaList from '../components/PizzaList'
import axios from 'axios'
import { useState } from 'react'
import Add from '../components/Add'
import AddButton from '../components/AddButton'
export default function Home({pizzaList,admin,piz}) {
  
  const [close,setClose]=useState(true);
  return (
    
    <div className={styles.container}>
      <Head>
        <title>ShobhiPizza</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"></link>
      </Head>
      <Featured/>
      {admin && <AddButton setClose={setClose}/>}
      {piz && <PizzaList pizzaList={pizzaList}/>}
      {(!close && <Add setClose={setClose}/>)}
    </div>
  )
}

export const getServerSideProps = async (ctx) => {
  const myCookie = ctx.req?.cookies || "";
  let admin = false;
  let piz=true;

  if (myCookie.token === process.env.TOKEN) {
    admin = true;
  }

  const res = await axios.get("http://localhost:3000/api/products")
  return {
    props: {
      pizzaList: res.data,
      admin,
      piz,
    },
  };
};